# Generated by Django 3.0.2 on 2020-06-24 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Электроэнергия', 'Электроэнергия'), ('Холодная вода', 'Холодная вода'), ('Горячая вода', 'Горячая вода')], max_length=50)),
                ('objfk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grr.obj')),
                ('paramfk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grr.param')),
            ],
        ),
        migrations.CreateModel(
            name='values_sens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem', models.DecimalField(decimal_places=4, max_digits=11)),
                ('dat', models.DateTimeField()),
                ('sensfk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grr.sens')),
            ],
        ),
        migrations.CreateModel(
            name='user_obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objfk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grr.obj')),
                ('userfk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
